# For all options see https://github.com/bbatsov/rubocop/tree/master/config

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'

LineLength:
  Max: 90

MethodLength:
  Max: 30

Metrics/AbcSize:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/DotPosition:
  EnforcedStyle: trailing

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Documentation:
  Enabled: false

Style/For:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
