require 'symmetric/kasiski'
require 'symmetric/vigenere_cipher'

RSpec.describe(Kasiski) do
  subject(:kasiski) { described_class.new(cipher_text) }

  # Uses a Vigenere cipher with key 'crypto'
  let(:plain_text)   { load_fixture('sample.vigenere.plaintext') }
  let(:cipher_text)  { load_fixture('sample.vigenere.encrypted') }

  describe('.key_size') do
    it 'guesses key size of cipher used' do
      expect(kasiski.key_size).to equal(6)
    end

    context 'with autogenerated cipher texts' do
      %w(cat fork table toffee caramel).each do |key|
        it "guesses key_size for '#{key}'" do
          expect(Kasiski.new(VigenereCipher.new(key).encode(plain_text)).key_size).
            to equal(key.size)
        end
      end
    end
  end
end
